db:
  dialect: mysql
  dsn: root:Hiep.vv!serious1@tcp(localhost:3306)/tikihackathon?timeout=10s&parseTime=true

log:
  mode: production
  type: zap

server:
  http:
    port: 8080

cache:
  ttl: 3600000000000 # 1h in ns
  cleanup_interval: 3600000000000  # 1h in ns

feed:
  default_offset: 0
  default_limit: 10
