db:
  dialect: postgres
  dsn: host=ec2-34-225-103-117.compute-1.amazonaws.com user=sttkbwhhbfzyis password=2bbb535543dcb4bf3effc10b8437d1982f42d10cd6a2a6eb74d8d61d307357e1 dbname=dba0he9ct5fqqm sslmode=disable Asia/Ho_Chi_Minh

log:
  mode: production
  type: zap

server:
  http:
    addr: :8080